# -*- coding: utf-8 -*-
"""UpdateDatatoPinecone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jn0ViVE35ufTF1P3zw_j4XSLwTGb7P71

References: https://docs.pinecone.io/docs/

Format of vector data:

 vectors=[
    {
      "id": "A",
      "values": [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
      "metadata": {"genre": "comedy", "year": 2020}
    },
    {
      "id": "B",
      "values": [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
      "metadata": {"genre": "documentary", "year": 2019}
    },
    {
      "id": "C",
      "values": [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3],
      "metadata": {"genre": "comedy", "year": 2019}
    },
    {
      "id": "D",
      "values": [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
      "metadata": {"genre": "drama"}
    }
  ]
)
"""

# !pip install pinecone-client
# !pip install langchain
#!pip install -U langchain-openai

from langchain_openai import OpenAIEmbeddings
from langchain.schema import Document

import pandas as pd
from tqdm import tqdm
import os, time
from itertools import islice


ENVIRONMENT = 'gcp-starter'

from pinecone import Pinecone, ServerlessSpec
pc = Pinecone(api_key= os.environ(PINE_API_KEY), environment = ENVIRONMENT)

pc

myindex = pc.Index(host=os.environ(HOSTNAME)
#OpenAI Config
token = os.environ(API_KEY)

model_name = 'text-embedding-ada-002'
embed = OpenAIEmbeddings(model=model_name,openai_api_key=token)

df = pd.read_csv('/content/recipes_finalv1.csv', on_bad_lines='skip')
df = df.fillna('')
df=df[:1000]

df.rename(columns={ df.columns[0]: "ID" },inplace=True)

df.columns

myindex.describe_index_stats()

# Get description vectors and metadata
veci = df['Description']
mdata = df.drop(columns=['Description','ID'])
id = df['ID']

texts_to_embed = veci.tolist()

embeddings = embed.embed_documents(texts_to_embed)

len(embeddings)

dict_data = mdata.to_dict(orient='records')
print(dict_data)

for i in range(len(id)):
    myindex.upsert(vectors=[{"id": id[i], "values": embeddings[i], "metadata": dict_data[i]}])
print("Successfully updated to db!")

#########################################################################################################################################